### ISSUE TITLE
Run-time performance improvements

### ISSUE THREAD

**Issue by wuhu** [lf1-io/padl#342]
## caching + removing contexts

https://github.com/lf1-io/padl/pull/341

## speed up `infer_apply`

There is some overhead by calling the three stages separately.
We could potentially speed it up by moving `move_to_device` back into `Batchify` and calling the transform as a whole. @jasonkhadka do you remember why we pulled it out?

Potentially remove `forward_device_check` - it seems to be wasteful to check every time. Alternative is to not check and make people figure it out themselves when they run into the runtime error.

**Comment by sjrl** [comment]
To give some context on PR #341. @wuhu and I realized that the creation of the context manager and not using caching was causing overhead when calling any transform with `pd_call_transform` (~5-10 times slower). We realized that this can become a significant issue during training due to `pd_call_transform` being called by each worker in the DataLoader for every data point. With the changes in PR #341 (so far) the overhead is reduced to (~3 times).

**Comment by sjrl** [comment]
@wuhu I think it might be worth revisiting if we could call this code only once for each of the `_apply` methods instead of calling it each time `pd_call_in_mode`.
```python
        if no_grad:
            grad_before = torch.is_grad_enabled()
            torch.set_grad_enabled(False)

        try:
            return self._pd_unpack_args_and_call(arg)
        finally:
            if mode is not None:
                for i, training in enumerate(training_before):
                    layer = layers[i]
                    if training:
                        layer.train()
                    else:
                        layer.eval()
            Transform.pd_mode = None
            if no_grad:
                torch.set_grad_enabled(grad_before)
```
I know we made this decision in the scenario that the user created two iterators with different modes (e.g. using `train_apply` and `eval_apply`). However, I don't think this safety is worth the overhead this creates in the `DataLoader` with the `preprocess.pd_call_in_mode` call and in the `postprocess` call, which we call in serial at the moment.

What do you think?

**Comment by wuhu** [comment]
closing for now
