### ISSUE TITLE
`lf_component` mapping and `preprocess, forward, postprocess` breakdown does not work in some edge cases

### ISSUE THREAD

**Issue by jasonkhadka** [lf1-io/padl#97]
Example:
```python
model_3 = (
    plus_one + times_two
    >> plus_one / Batchify()
    >> plus_one / plus_one
    >> Batchify() / times_two
    >> Unbatchify()
    >> plus_one
)
```

`pd_preprocess`
```python
(
    plus_one + times_two)
    >> (plus_one / lf.Batchify())
    >> (plus_one / plus_one)
    >> (lf.Batchify() / lf.Identity()
    )
```

`pd_forward`
```python
(lf.Identity() / times_two)
```

`pd_postprocess`
```python
(
    lf.Unbatchify() 
    >> plus_one
)
```

**Comment by wuhu** [comment]
I've drafted a solution here: https://github.com/lf1-io/padl/pull/230

The idea is to implement a method `_pd_splits` for the different Transform classes which takes the component configuration of the input (i.e. information about which parts of the input are untouched, batchified, or unbatchified) and returns a 3-tuple of (preprocess, forward, postprocess)- parts and the output component configuration.
It seems that by having the precise input component configuration available everywhere, instead of using the `_pd_component` - set, makes it possible to solve the problem.

The above example works, it is split into:

Preprocess:
```
Compose:

      └──────────┐
      │          │
      ▼ x        ▼ x
   0: plus_one + times_two      
      │          │
      ▼ x        ▼ args
   1: plus_one / padl.Identity()
      │          │
      ▼ x        ▼ args
   2: plus_one / padl.Identity()
   ```

Forward:

```
Compose:

      └──────────┐
      │          │
      ▼ x        ▼ x
   0: plus_one + times_two      
      │          │
      ▼ x        ▼ args
   1: plus_one / padl.Identity()
      │          │
      ▼ x        ▼ args
   2: plus_one / padl.Identity()
```

Postprocess:

```
plus_one:

   def plus_one(x):
       return x + 1
```
